// Extracts the notehead outlines we use from the Bravura music font and writes
// them to src/lib/glyphs.ts, so the app ships plain SVG paths and never has to
// load a font at runtime.
//
// Run with: npm run build:glyphs
//
// Bravura is (c) Steinberg Media Technologies GmbH, SIL Open Font License 1.1.
// Coordinates are converted from font units into *staff spaces* (SMuFL puts one
// staff space at a quarter of the em) and flipped, since the font's y axis
// points up and SVG's points down. A caller only has to scale by its line gap.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import opentype from 'opentype.js';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '../node_modules/@vexflow-fonts/bravura');
const out = join(here, '../src/lib/glyphs.ts');

// The glyphs we draw, by SMuFL codepoint.
const GLYPHS = {
	noteheadWhole: 0xe0a2,
	noteheadHalf: 0xe0a3,
	noteheadBlack: 0xe0a4
};

// Key signature accidentals. Flats are here for the flat keys the activity does
// not teach yet — they cost nothing to carry and save regenerating later.
const ACCIDENTALS = {
	accidentalSharp: 0xe262,
	accidentalFlat: 0xe260,
	accidentalNatural: 0xe261
};

const font = opentype.parse(readFileSync(join(pkg, 'bravura.otf')).buffer);
const metadata = JSON.parse(readFileSync(join(pkg, 'metadata.json'), 'utf8'));

// SMuFL: the em square spans four staff spaces.
const perSpace = font.unitsPerEm / 4;
const round = (n) => Number((n / perSpace).toFixed(4));

function pathFor(codepoint) {
	const glyph = font.charToGlyph(String.fromCodePoint(codepoint));
	if (!glyph || glyph.index === 0) throw new Error(`missing glyph U+${codepoint.toString(16)}`);
	// getPath already emits SVG's downward y axis, so do NOT negate again here.
	// (Anchors, which come from the metadata in the font's upward axis, do.)
	return glyph
		.getPath(0, 0, font.unitsPerEm)
		.commands.map((c) => {
			switch (c.type) {
				case 'M':
				case 'L':
					return `${c.type}${round(c.x)} ${round(c.y)}`;
				case 'C':
					return `C${round(c.x1)} ${round(c.y1)} ${round(c.x2)} ${round(c.y2)} ${round(c.x)} ${round(c.y)}`;
				case 'Q':
					return `Q${round(c.x1)} ${round(c.y1)} ${round(c.x)} ${round(c.y)}`;
				case 'Z':
					return 'Z';
				default:
					throw new Error(`unexpected path command ${c.type}`);
			}
		})
		.join('');
}

// The stem anchors sit on the widest point of the notehead, so each one must
// land on an on-curve point of the outline. If the path and the anchors ever
// disagree about which way is up, the stem detaches from the head — so check.
function assertAnchorsOnOutline(name, path, anchors) {
	const onCurve = [...path.matchAll(/[MLC]([-\d. ]+)/g)].map((m) => {
		const n = m[1].trim().split(/\s+/).map(Number);
		return [n[n.length - 2], n[n.length - 1]];
	});
	for (const [anchorName, point] of Object.entries(anchors)) {
		const hit = onCurve.some(
			([x, y]) => Math.abs(x - point[0]) < 0.01 && Math.abs(y - point[1]) < 0.01
		);
		if (!hit) {
			throw new Error(
				`${name}: ${anchorName} [${point}] is not on the outline — ` +
					`the path is probably flipped relative to the anchors`
			);
		}
	}
}

// An accidental's origin is its left edge, on the line or space it sits on —
// the same convention as a notehead, so it is placed the same way.
const accidentals = Object.entries(ACCIDENTALS).map(([name, codepoint]) => {
	const bbox = metadata.glyphBBoxes[name];
	return {
		name,
		codepoint,
		key: name.replace('accidental', '').toLowerCase(),
		path: pathFor(codepoint),
		width: Number((bbox.bBoxNE[0] - bbox.bBoxSW[0]).toFixed(4))
	};
});

const entries = Object.entries(GLYPHS).map(([name, codepoint]) => {
	const bbox = metadata.glyphBBoxes[name];
	const anchors = metadata.glyphsWithAnchors[name] ?? {};
	const path = pathFor(codepoint);
	const stems = Object.fromEntries(
		['stemUpSE', 'stemDownNW']
			.filter((k) => anchors[k])
			.map((k) => [k, [anchors[k][0], -anchors[k][1]]])
	);
	assertAnchorsOnOutline(name, path, stems);
	return {
		name,
		codepoint,
		path,
		width: Number((bbox.bBoxNE[0] - bbox.bBoxSW[0]).toFixed(4)),
		...stems
	};
});

const d = metadata.engravingDefaults;
const source = `// GENERATED by scripts/build-glyphs.mjs — do not edit by hand.
//
// Notehead and accidental outlines from Bravura ${metadata.fontVersion}, the SMuFL
// reference font.
// Copyright (c) Steinberg Media Technologies GmbH, SIL Open Font License 1.1.
//
// All numbers are in *staff spaces*: multiply by the line gap to get pixels.
// The origin of each path is the glyph's left edge, vertically centred on the
// line or space it sits on, so a path is placed by translating to that point.
// Paths are pre-flipped for SVG's downward y axis.

export interface Glyph {
	/** Outline, in staff spaces, origin at the glyph's left edge and centre. */
	path: string;
	/** Width of the glyph, for centring or spacing it. */
	width: number;
	/** Where an upward stem meets the head (right side). */
	stemUpSE?: readonly [number, number];
	/** Where a downward stem meets the head (left side). */
	stemDownNW?: readonly [number, number];
}

// Bravura's recommended engraving metrics, in staff spaces.
export const ENGRAVING = {
	staffLineThickness: ${d.staffLineThickness},
	stemThickness: ${d.stemThickness},
	legerLineThickness: ${d.legerLineThickness},
	legerLineExtension: ${d.legerLineExtension},
	/** Conventional stem length, measured from the centre of the notehead. */
	stemLength: 3.5
} as const;

export const NOTEHEADS = {
${entries
	.map(
		(e) => `	// U+${e.codepoint.toString(16).toUpperCase()} ${e.name}
	${e.name.replace('notehead', '').toLowerCase()}: {
		path: '${e.path}',
		width: ${e.width}${e.stemUpSE ? `,\n\t\tstemUpSE: [${e.stemUpSE.join(', ')}]` : ''}${e.stemDownNW ? `,\n\t\tstemDownNW: [${e.stemDownNW.join(', ')}]` : ''}
	}`
	)
	.join(',\n')}
} as const satisfies Record<string, Glyph>;

// Key signature accidentals, placed like noteheads: translate to the left edge
// of the glyph, on the line or space it applies to.
export const ACCIDENTALS = {
${accidentals
	.map(
		(e) => `	// U+${e.codepoint.toString(16).toUpperCase()} ${e.name}
	${e.key}: {
		path: '${e.path}',
		width: ${e.width}
	}`
	)
	.join(',\n')}
} as const satisfies Record<string, Glyph>;
`;

writeFileSync(out, source);
console.log(`wrote ${out}`);
for (const e of [...entries, ...accidentals])
	console.log(`  ${e.name}: ${e.path.length} chars, width ${e.width}`);
